lib: improve error handling for SESL stub methods.
Since Throwable includes both Errors and Exceptions,
this should effectively catch java.lang.NoSuchMethodError
and prevent crash caused by it.

Signed-off-by: tribalfs <tribalfs@gmail.com>